project_id = "tbdooscfrrkwfutkdjha"

[functions.criar-gravacao-automatica]
verify_jwt = true

[functions.sync-pops-drive]
verify_jwt = false

[functions.analisar-transcricao]
verify_jwt = true

[functions.clickup-integration]
verify_jwt = false